/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/barcode-scanner`; params?: Router.UnknownInputParams; } | { pathname: `/bill-payment`; params?: Router.UnknownInputParams; } | { pathname: `/credit-card`; params?: Router.UnknownInputParams; } | { pathname: `/debit-purchase`; params?: Router.UnknownInputParams; } | { pathname: `/extrato`; params?: Router.UnknownInputParams; } | { pathname: `/financial-summary`; params?: Router.UnknownInputParams; } | { pathname: `/pix-credit`; params?: Router.UnknownInputParams; } | { pathname: `/pix-receipt`; params?: Router.UnknownInputParams; } | { pathname: `/pix-scheduled`; params?: Router.UnknownInputParams; } | { pathname: `/pix`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/devtools` | `/devtools`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/metrics` | `/metrics`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/barcode-scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/bill-payment`; params?: Router.UnknownOutputParams; } | { pathname: `/credit-card`; params?: Router.UnknownOutputParams; } | { pathname: `/debit-purchase`; params?: Router.UnknownOutputParams; } | { pathname: `/extrato`; params?: Router.UnknownOutputParams; } | { pathname: `/financial-summary`; params?: Router.UnknownOutputParams; } | { pathname: `/pix-credit`; params?: Router.UnknownOutputParams; } | { pathname: `/pix-receipt`; params?: Router.UnknownOutputParams; } | { pathname: `/pix-scheduled`; params?: Router.UnknownOutputParams; } | { pathname: `/pix`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/devtools` | `/devtools`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/metrics` | `/metrics`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/barcode-scanner${`?${string}` | `#${string}` | ''}` | `/bill-payment${`?${string}` | `#${string}` | ''}` | `/credit-card${`?${string}` | `#${string}` | ''}` | `/debit-purchase${`?${string}` | `#${string}` | ''}` | `/extrato${`?${string}` | `#${string}` | ''}` | `/financial-summary${`?${string}` | `#${string}` | ''}` | `/pix-credit${`?${string}` | `#${string}` | ''}` | `/pix-receipt${`?${string}` | `#${string}` | ''}` | `/pix-scheduled${`?${string}` | `#${string}` | ''}` | `/pix${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/devtools${`?${string}` | `#${string}` | ''}` | `/devtools${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/metrics${`?${string}` | `#${string}` | ''}` | `/metrics${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/barcode-scanner`; params?: Router.UnknownInputParams; } | { pathname: `/bill-payment`; params?: Router.UnknownInputParams; } | { pathname: `/credit-card`; params?: Router.UnknownInputParams; } | { pathname: `/debit-purchase`; params?: Router.UnknownInputParams; } | { pathname: `/extrato`; params?: Router.UnknownInputParams; } | { pathname: `/financial-summary`; params?: Router.UnknownInputParams; } | { pathname: `/pix-credit`; params?: Router.UnknownInputParams; } | { pathname: `/pix-receipt`; params?: Router.UnknownInputParams; } | { pathname: `/pix-scheduled`; params?: Router.UnknownInputParams; } | { pathname: `/pix`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/devtools` | `/devtools`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/metrics` | `/metrics`; params?: Router.UnknownInputParams; };
    }
  }
}
